# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Text(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, text: str=None):  # noqa: E501
        """Text - a model defined in Swagger

        :param text: The text of this Text.  # noqa: E501
        :type text: str
        """
        self.swagger_types = {
            'text': str
        }

        self.attribute_map = {
            'text': 'text'
        }

        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'Text':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Text of this Text.  # noqa: E501
        :rtype: Text
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self) -> str:
        """Gets the text of this Text.


        :return: The text of this Text.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this Text.


        :param text: The text of this Text.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text
