# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TextQuery(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, text: str=None, query: List[str]=None):  # noqa: E501
        """TextQuery - a model defined in Swagger

        :param text: The text of this TextQuery.  # noqa: E501
        :type text: str
        :param query: The query of this TextQuery.  # noqa: E501
        :type query: List[str]
        """
        self.swagger_types = {
            'text': str,
            'query': List[str]
        }

        self.attribute_map = {
            'text': 'text',
            'query': 'query'
        }

        self._text = text
        self._query = query

    @classmethod
    def from_dict(cls, dikt) -> 'TextQuery':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TextQuery of this TextQuery.  # noqa: E501
        :rtype: TextQuery
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self) -> str:
        """Gets the text of this TextQuery.


        :return: The text of this TextQuery.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this TextQuery.


        :param text: The text of this TextQuery.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def query(self) -> List[str]:
        """Gets the query of this TextQuery.


        :return: The query of this TextQuery.
        :rtype: List[str]
        """
        return self._query

    @query.setter
    def query(self, query: List[str]):
        """Sets the query of this TextQuery.


        :param query: The query of this TextQuery.
        :type query: List[str]
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")  # noqa: E501

        self._query = query
